# ==============================================================
#  GitHub Actions CI/CD Workflow
#  Deploy FastAPI (alz-backend) to Azure App Service
#  Features:
#   ✅ Python 3.11 environment
#   ✅ PIP caching for faster builds
#   ✅ Clean artifact upload (no virtualenv)
#   ✅ Azure handles pip install via Oryx
# ==============================================================

name: Build and deploy Python app to Azure Web App - alz-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # ------------------------------------------------------------
  # BUILD JOB
  # ------------------------------------------------------------
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # NOTE: No local virtual environment build — Azure will install dependencies
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: .

  # ------------------------------------------------------------
  # DEPLOY JOB
  # ------------------------------------------------------------
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4AFF8F14325243C893BE64FD1A03D50A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D8F63D91A34240BB87B368DF89982E5E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A186610FD6184413995093736EA804EF }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'alz-backend'
          slot-name: 'Production'
